# Generated by Django 4.2.24 on 2025-09-05 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lrn_org", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lesson",
            old_name="title",
            new_name="name",
        ),
    ]
