# Generated by Django 5.2.5 on 2025-11-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lrn_org", "0003_area_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="content",
            field=models.TextField(blank=True, default=""),
        ),
    ]
